version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: motion-budgets
      POSTGRES_PASSWORD: motion
      POSTGRES_DB: motion-budgets
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
